# Generated by Django 5.1 on 2024-11-17 13:21

import datetime
import django.core.validators
import django.db.models.deletion
import reservation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, validators=[reservation.models.Reservation.validate_date]),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_booked',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 11, 17, 13, 21, 0, 105971)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.CharField(choices=[('12:30', '12:30'), ('13:30', '13:30'), ('14:30', '14:30'), ('15:30', '15:30'), ('16:30', '16:30'), ('17:30', '17:30'), ('18:30', '18:30'), ('19:30', '19:30'), ('20:30', '20:30'), ('21:30', '21:30')], default='12:30', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
