# Generated by Django 4.2 on 2025-03-26 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_date_reservation_date_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_booked',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 26, 19, 50, 34, 597743)),
        ),
    ]
